{{- if .Values.terraformHealth.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: terraformdrift
type: Opaque
data:
{{- range $pkey, $pval := .Values.terraformHealth.secretEnv }}
  {{ $pkey }}: {{ $pval | b64enc }}
{{- end }}
{{- end }}
