apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: terraform-drift
build:
  artifacts:
    - image: mellardc/terraform-health
      context: cmd/terraform-drift
      docker:
deploy:
  helm:
    releases:
      - name: terraform-drift
        chartPath: charts/terraform-drift-check
        artifactOverrides:
          terraformHealth:
            image:
              repository: mellardc/terraform-health
        setValueTemplates:
          terraformHealth:
            secretEnv:
              GIT_TOKEN: "{{.GIT_TOKEN}}"
              ARM_CLIENT_SECRET: "{{.ARM_CLIENT_SECRET}}"
        namespace: kuberhealthy
